# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Matheus Paro Ferreira
title: Information Systems Management Student
email: mferreira.ieu2017@student.ie.edu
website: https://matheusparo.github.io/

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: facespics
github_username:  MatheusParo
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: paromatheus
linkedin_username: matheusparo
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hello there! My name is Matheus and I am a senior student at IE University. I'm Brazilian and fascinated by technology, whether it comes to Machine Learning, Software Development or IT Opertaions or Digital Strategy, I will use my learning to work as best as I can.

  I am most skilled in: <mark>Python</mark> and <mark>Tech Consultancy</mark>

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Super awesome project
        link: github.com/matheusparo
        # link_text: Project Website
        additional_links:
        #  - title:  sproogen/modern-resume-theme
        #    icon: fab fa-github
        #    url: github.com/sproogen/modern-resume-theme
          - title:  MatheusParo/Forecasting-Passengers-in-Airports-with-SVR
            icon: fab fa-github
            url: matheusparo.github.io/test
        quote: >
          You can access all my past and ongoing projects in the link above.
        description: | # this will include new lines to allow paragraphs
          Although I love to manage Machine learning projects, I have tried to diversify as much as I can. When in university we used github to document most of our projects.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Co-Founder
        link: opentabs.org
        # link_text: boringcompany.com
        sub_title: CTO
        caption: January 2018 - January 2020
        quote: >
            A poverty-tackling NGO that provides microfinancing to low-income micro-entrepreneurs and families in developing countries.
        description: | # this will include new lines to allow paragraphs
            My experience at OpenTabs was one of growth as I learnt all about web development from zero by myself. I learnt from the best of web development tools, such as <mark>HTML</mark>, <mark>CSS</mark>, <mark>PHP</mark>, file management systems and other database management tools such as <mark>SQL</mark> and <mark>JavaScript</mark>. This was very important as it served as the foundation for the further iterations of the Extension and Website.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: IE University
        caption: 2017 - 2021
        sub_title: BISM (Information Systems Management)
        quote: >
          A bachelor that includes both Business and IT systems studies, focused on companies.
        description: | # this will include new lines to allow paragraphs
          Learnt object oriented programming with <mark>Java</mark> and how to come up with fast machine learning models with <mark>Python</mark>.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Having lived all across the world, I learnt to look at everything from a different perspective. I was fortunate enough to live in the following countries:
      - Switzerland
      - United States
      - Mexico
      - Brazil
      - Spain
      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

      Look at this cool image
      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
